# Generated by Django 2.0.2 on 2021-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190415_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
